### ISSUE TITLE
Can't find Windows cmd.exe binaries

### ISSUE THREAD

**Issue by bulrush15** [sheabunge/GitPortable#13]
I'm having trouble finding binaries for a Windows cmd.exe box. DO you have the link for that? Thanks.

**Comment by dansmith65** [comment]
Here is my cmd.exe from a Windows 8.1 computer: https://dl.dropboxusercontent.com/u/38687808/cmd.zip

Is that all you needed?

**Comment by sheabunge** [comment]
I'm not entirely sure what you mean by 'finding binaries'. If you're looking for the `git.exe` and related binaries, they are available under `App\Git\bin`. Otherwise you can just launch `GitPortable.exe
