### ISSUE TITLE
bash.exe: warning: could not find /tmp, please create!

### ISSUE THREAD

**Issue by GordCaswell** [sheabunge/GitPortable#17]
I utilize Git Portable via the git GUI exclusively, and I am continuing to received the above error when pushing to repos, including using 2.7.2 DT1.

I see in both launcher's ini's that PATH is not set as an Environment Variable, possibly this is why?

**Comment by sheabunge** [comment]
Hmm, I'll have a look at it and see if that's the issue.

**Comment by sheabunge** [comment]
Resolved by #18
