### ISSUE TITLE
cannot find menu "git pull" in GitGUIPortable.exe

### ISSUE THREAD

**Issue by amin007** [sheabunge/GitPortable#22]

**Comment by GordCaswell** [comment]
Does it exist in the git gui available from git-scm.com? particularly the portable version offered there?

**Comment by amin007** [comment]
interface git portable
https://github.com/amin007/phparastinggi/blob/gh-pages/imgs/git/interface-git.png

i like interface like tortoigit
https://github.com/amin007/phparastinggi/blob/gh-pages/imgs/git/interface-tortoigit.png

**Comment by GordCaswell** [comment]
You misunderstand. We don't develop the git gui, that's done by the folks at https://github.com/git/git

You'll need to request the feature from them, not us.

**Comment by amin007** [comment]
ok, thank you
