### ISSUE TITLE
gitk launcher

### ISSUE THREAD

**Issue by GordCaswell** [sheabunge/GitPortable#23]
Git Portable currently includes launchers for git (bash), and git-gui. As it is possible to launch gitk with the base app, I propose that a launcher be created as well.

**Comment by amin007** [comment]
ok

**Comment by GordCaswell** [comment]
I am closing this issue. When releasing an application, only under very specific circumstances is it allowed to have more than one launcher. Git Portable doesn't meet the criteria.
