### ISSUE TITLE
bash.exe: warning: could not find /tmp, please create!

### ISSUE THREAD

**Issue by chirag-prajapati-2705** [sheabunge/GitPortable#25]
I am facing this issue so anyone has a solution then let me know. I have stuck on this issue.

**Comment by 3D1T0R** [comment]
This has been a regular problem in the past, but I thought it was fixed in recent versions. ☹️ 

**A few questions, if you will:**
What were you doing when the issue occurred?
What version of Git Portable are you running?
How are you running it?

**Comment by jgonyea** [comment]
I know this is an old issue, but I ran into an odd problem with my tmp folder as well.  I resolved it by:

- Closing the git program
- Deleting the tmp folder found at E:\PortableApps\GitPortable\App\Git\tmp, where "E" is your drive letter.
- Reopen the git program (which should auto-recreate the tmp folder)

**Comment by sheabunge** [comment]
@chirag-prajapati-2705, can you confirm whether the advice offered by @jgonyea resolves this issue?

I'm going to close this for now, pending further response.
