### ISSUE TITLE
Launching git-bash vs git-gui from menu

### ISSUE THREAD

**Issue by jgonyea** [sheabunge/GitPortable#26]
Is it safe to change the App\AppInfo\Launcher\GitPortable.ini to launch git-bash instead of the git-gui?  I'd prefer that the menu entry the git bash (or maybe we could have an additional menu item that does this?)

Thanks in advance.

**Comment by Murmur** [comment]
I just realized this same change after downloading and installing `Git Portable 2.13.0 Development Test 1` paf package to an existing c:/apps/GitPortable/ folder.  This package did not include GitGUIPortable.exe anymore and GitPortable.exe started a gitgui window app.

My old package is git-gui/0.20,git/2.5.3.windows.1 version. It installed `GitPortable/GitPortable.exe (runs git-bash console)` and `GitPortable/GitGUIPortable.exe (runs gitgui window)` files. I prefer git-bash console interface.

**Comment by amin007** [comment]
can user choose between gui and terminal?

**Comment by jgonyea** [comment]
@amin007 I manually changed the file in the opening issue, and I was able to load Git bash direct from the PA menu. It appears to work great for me.

**Comment by Murmur** [comment]
This is how I fixed a default launch application, I want git-bash console to open when `C:\apps\GitPortable\GitPortable.exe` is run.
**C:\apps\GitPortable\App\AppInfo\Launcher\GitPortable.ini**
```
[Launch]
#ProgramExecutable=Git\cmd\git-gui.exe
ProgramExecutable=Git\git-bash.exe
WorkingDirectory=%PAL:DataDir%\home
...rest of the content...
```

Home folder is `C:\apps\GitPortable\Data\home\`  where .bashrc file and .ssh subfolder are located, such as this bashrc content to provide few custom shortcut commands.

**C:\apps\GitPortable\Data\home\\.bashrc**
```
# Git-friendly prompt showing dirty state
# http://stackoverflow.com/questions/10133173/alter-git-prompt-on-windows

shopt -s promptvars
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWUPSTREAM='verbose git'
export PS1='\[\033[1;36m\]\[\033[0m\]\[\033[1;34m\]\w\[\033[0m\] 
\[\033[1;32m\]$(__git_ps1)\[\033[0m\]\$ '

# Enable color support of ls
alias ls='ls --color=auto -alhX'

## shortcut cmdline 
function gogitbase
{
  cd /c/gitbase/
}

function goproject
{
  cd /c/projects/
}
```

**Comment by jgonyea** [comment]
This PR adds both menu items to the PA menu.
https://github.com/sheabunge/GitPortable/pull/38

**Comment by sheabunge** [comment]
Closing thanks to the PR by @jgonyea
