### ISSUE TITLE
Git bash application launcher disapeared

### ISSUE THREAD

**Issue by AyoMoses** [sheabunge/GitPortable#27]
Was working on git bash and opened another bash terminal and then both closed and the application launcher went missing on C:\Program Files\Git. Hope i can get a solution to this.

**Comment by jgonyea** [comment]
I have noticed that a local install git-bash and a portable git-bash can't be opened at the same time.  Does rebooting your computer bring back  the reference to the local install?

**Comment by AyoMoses** [comment]
Apologies for replying this late having solved it by re installing git again.
