### ISSUE TITLE
Install up-to-date git on top of the existing GitPortable installation

### ISSUE THREAD

**Issue by Murmur** [sheabunge/GitPortable#28]
If you want up-to-date git binaries this is how I made a fresh GitPortable installation.

**https://github.com/sheabunge/GitPortable**
- Install GitPortable_2.13.0_Development_Test_1.paf.exe
- this file provides basic portable files but git application is quite old
- my installation goes to `C:\apps\GitPortable\` folder

**https://github.com/git-for-windows/git/releases**
- Download PortableGit-2.17.0-64-bit.7z.exe (or newer) to have up-to-date git application
- extract executable to a temporary folder
- run postinstall.bat script in a temporary folder
- rename existing `C:\apps\GitPortable\App\Git` to Git_OLD folder
- copy new files to `C:\apps\GitPortable\App\Git` folder
- delete Git_OLD after few days if all working fine

**C:\apps\GitPortable\Data\home**
- this is a git console home folder where .ssh folder and other bashrc settings are stored

**C:\apps\GitPortable\App\AppInfo\Launcher\GitPortable.ini**
- edit ini file to change executable to bash console
```  
  [Launch]
  #ProgramExecutable=Git\cmd\git-gui.exe
  ProgramExecutable=Git\git-bash.exe
```
- run `C:\apps\GitPortable\GitPortable.exe` to open a bash console

**C:\apps\GitPortable\Data\home\\.bashrc**
- edit bashrc settings, provide few shortcut commands
```
# Git-friendly prompt showing dirty state
# http://stackoverflow.com/questions/10133173/alter-git-prompt-on-windows

shopt -s promptvars
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWUPSTREAM='verbose git'
export PS1='\[\033[1;36m\]\[\033[0m\]\[\033[1;34m\]\w\[\033[0m\] 
\[\033[1;32m\]$(__git_ps1)\[\033[0m\]\$ '

# Enable color support of ls
alias ls='ls --color=auto -alhX'

## shortcut cmdline 
function gogitbase
{
  cd /c/sd/gitbase/
}

function goproject
{
  cd /c/projects/
}
```

**Comment by sheychen290** [comment]
May be script that in a new GitPortable_Lastest.online.paf.exe

**Comment by amin007** [comment]
+1

**Comment by jgonyea** [comment]
New version of the source code should now pull the latest git version (2.20.1 as of writing) automatically.
