### ISSUE TITLE
Traojan warning

### ISSUE THREAD

**Issue by vkuehn** [sheabunge/GitPortable#29]
The latest release version causes this antivirus complain

[Trojan.Gen.2](https://www.symantec.com/security-center/writeup/2011-082216-3542-99?vid=41129)

can you kindly check ?

**Comment by GordCaswell** [comment]
This is known as a "false positive", as the download has been verified clean here: https://www.virustotal.com/#/file/ace8738cbb48c031efb0b98cbb94ffaa4f915da8c393d4525d7951b39c59e244/detection
