### ISSUE TITLE
Submit to PA.com

### ISSUE THREAD

**Issue by jgonyea** [sheabunge/GitPortable#34]
Would you consider submitting this app to the PA.com official repo?  I'd be happy to help support it, should it be accepted.  I use this build near daily.

Thanks

**Comment by sheabunge** [comment]
Git Portable has been waiting for review on PortableApps.com for a while now. I'm not aware of a way to speed up this process, unfortunately.

https://portableapps.com/development/test

**Comment by sheabunge** [comment]
I have updated the info on PortableApps.com, so I'm closing this issue for now.
