### ISSUE TITLE
post-install.bat is not run after install

### ISSUE THREAD

**Issue by blandin** [sheabunge/GitPortable#35]
From README.portable in PortableGit-*.7z.exe:
```
*NOTE*: if you decide to unpack the archive using 7-Zip manually, you must
run the `post-install.bat` script. Git will not run correctly
otherwise.
```
After examining the contents of post-install.bat, it appears to be of particular importance for a 32-bit build of Git, which is in use here.

**Comment by sheabunge** [comment]
Thanks for this. I've made running it a part of the install process.
