### ISSUE TITLE
general questions

### ISSUE THREAD

**Issue by jim1001** [sheabunge/GitPortable#36]
Think I'm missing something...

The Readme file says 

> It will download Git for Windows as part of the install process.

Does that mean download _and_ install?

Does that  mean Git for Windows non-portable? If so, in what way is this a portable version? 

Thanks for any replies.

**Comment by sheabunge** [comment]
The install process here refers to installing Git Portable as a portable app, not the process of installing Git locally on a computer.

The line you refer to just means that the Git for Windows binaries will be downloaded while setting up the portable app.

**Comment by jim1001** [comment]
Thanks for reply.

Maybe part of my confusion was that I first "installed" the portable  app by downloading the self-extracting zip (.exe) file. 
 
I should probably try the latest  .paf.exe installer you’ve kindly provided (under Releases on GitHub) to see what happens.  It doesn’t appear on the Portable Apps platform or website because it’s still in testing - that right? 

However in meantime I've gone for a full local install so may come back at a later date!

Thanks again for your efforts.

**Comment by sheabunge** [comment]
I'm not 100% sure what the process for actually being listed on portableapps.com is. I've had it submitted for review for years now, but it doesn't seem many community-packaged apps are actually looked at.

The .paf.exe installer is what will allow Git Portable to properly install. It won't do a local install; it just copes the necessary files to the drive or folder you specify and runs a setup script.

Alternatively, it's possible to do these things manually, as is listed in the readme file, but using the installer is a lot easier.
