### ISSUE TITLE
GitPortable is not portable

### ISSUE THREAD

**Issue by CaliforniaMountainSnake** [sheabunge/GitPortable#41]
I just downloaded the portable package from the https://git-scm.com/download/win and extracted this for some directory.

Then i got some configuration:
```bash
git config --global commit.gpgsign
```
And this command returned `true` exactly like the main installed version.
Command history is also the same. What is **portable** in this portable edition?

**Comment by sheabunge** [comment]
You installed the regular version of Git for Windows, not the PortableApps.com-packaged version from this repository.

You can download the installer from https://github.com/sheabunge/GitPortable/releases/latest

Once downloaded, open Git by clicking on the GitBashPortable.exe launcher. Running a command like `git config --list --show-origin` will confirm that configuration is being loaded from the `GitPortable/Data/home/.gitconfig` file instead of from the local machine.

**Comment by CaliforniaMountainSnake** [comment]
Thanks, https://github.com/sheabunge/GitPortable/releases/latest version seems really portable.

But I don't understand why this version is not portable:
![Screenshot_41](https://user-images.githubusercontent.com/44233829/84640873-ef6e4c80-af02-11ea-976c-d4eb16446f11.png)

**Comment by sheabunge** [comment]
That is a different product, released by the [Git for Windows](https://github.com/git-for-windows/git) project. It may be a little misleadingly named, but have nothing to do with its development or release whatsoever, so you'll need to take it up with them.

Nevertheless, the lack of true portability in that project is what makes this one useful – it adds the portable configuration possibilities that aren't present in the aforementioned project.

**Comment by LeonT-A** [comment]
> 
> 
> Nevertheless, the lack of true portability in that version is primarily what makes this one useful – it adds the portable configuration possibilities that aren't present in the original project.

May I ask what these are?

I use a compiled python script to set a custom [HOME ](https://github.com/git-for-windows/git/issues/320#issuecomment-664698560) variable (as-well as others) to a folder and then launch git-bash.exe. Before doing this things would get written to my C:\Users\USERNAME folder, but after this I don't see anything being left behind by either Git-Bash or its built-in programs.

Just curious if there's something more I'm missing with my setup that you include in yours.

**Comment by sheabunge** [comment]
@LeonT-A This package of Git for Windows uses the PortableApps.com launcher configuration to set the HOME variable to a portable data folder, as well as rewriting absolute paths in `.gitconfig` to prevent things from breaking if the directory or drive letter changes.
