### ISSUE TITLE
Relatives paths in git config

### ISSUE THREAD

**Issue by mMontu** [sheabunge/GitPortable#7]
First of all, thank you very much for making Git available in PortableApps format!

I'm trying to configure git `core.editor` and `merge.tool` to gVimPortable, which is available at PortableApps.

The problem is that Git Bash opens in root directory, which is mapped to `PortableApps\GitPortable\App\Git`. I've tried executing gVim from this directory using `../../../gVimPortable.exe`, but it didn't work.

Is there any commands/variables indicating the path to current dir, which I can use to create a relative path to gVimPortable? Or is it possible to change the root directory to one above `GitPortable`?

**Comment by sheabunge** [comment]
I've updated the configuration to replace paths with forward slashes instead of backward, so from the next release (1.7.2 Dev Test 1) everything should be working as desired.

**Comment by mMontu** [comment]
Thanks!
